name: 'SecretPage'
description: 'Generate a secret page in GitHub.'
inputs:
  src:
    description: 'directory path to source files'
    required: true
  dist:
    description: 'directory path to distribution files'
    required: true
  password:
    description: 'aes password'
    required: false
outputs:
  ret:
    description: 'return code'
runs:
  using: 'docker'
  image: 'Dockerfile'
